version: '3.8'  # Use a modern version of Compose

services:
  nextjs: 
    build: .  # Build the image from the Dockerfile in the current directory
    container_name: nextAppContainer 
    restart: always  # Restart the container if it crashes
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on your host
    environment: 
      # Add any environment variables your app needs here
      # For example: DATABASE_URL=your_database_connection_string
 
  # nginx:
  #   image: nginx:alpine 
  #   container_name: my-nginx-proxy 
  #   restart: always
  #   ports:
  #     - "80:80" # Make your app accessible on port 80 of the host machine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your custom Nginx config
  #   depends_on:
  #     - nextjs # Ensure Next.js is running before starting Nginx
